version: '3.8'
services:
  springboot-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: karanmalhotra17/kmjenkins:tagkm   # tag it for push later
    ports:
      - "9090:8080"
